#define NUITKA_COMPANY_NAME "NSTIOM"
#define NUITKA_PRODUCT_NAME "Control Wi-Fi"
#define NUITKA_VERSION_COMBINED "0.1.2.0-1.3.0.0"
#define _NUITKA_ONEFILE_BUILD_BOOL 1
#define _NUITKA_ONEFILE_CHILD_GRACE_TIME_INT 5000
#define _NUITKA_ONEFILE_COMPRESSION_BOOL 1
#define _NUITKA_ONEFILE_TEMP_BOOL 1
#define _NUITKA_ONEFILE_TEMP_SPEC "%TEMP%\\onefile_%PID%_%TIME%"
